# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Venv_Projects/DroneKitTry/Codes/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 548)
        MainWindow.setMinimumSize(QtCore.QSize(1085, 548))
        MainWindow.setMaximumSize(QtCore.QSize(1085, 548))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(900, 40, 131, 252))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DsgnBattery = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.DsgnBattery.setFont(font)
        self.DsgnBattery.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DsgnBattery.setAlignment(QtCore.Qt.AlignCenter)
        self.DsgnBattery.setObjectName("DsgnBattery")
        self.verticalLayout.addWidget(self.DsgnBattery)
        self.DsgnAltitude = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.DsgnAltitude.setFont(font)
        self.DsgnAltitude.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DsgnAltitude.setAlignment(QtCore.Qt.AlignCenter)
        self.DsgnAltitude.setObjectName("DsgnAltitude")
        self.verticalLayout.addWidget(self.DsgnAltitude)
        self.DsgnSpeed = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.DsgnSpeed.setFont(font)
        self.DsgnSpeed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DsgnSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.DsgnSpeed.setObjectName("DsgnSpeed")
        self.verticalLayout.addWidget(self.DsgnSpeed)
        self.DsgnYaw = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.DsgnYaw.setFont(font)
        self.DsgnYaw.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DsgnYaw.setAlignment(QtCore.Qt.AlignCenter)
        self.DsgnYaw.setObjectName("DsgnYaw")
        self.verticalLayout.addWidget(self.DsgnYaw)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 40, 215, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblBat = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.lblBat.setFont(font)
        self.lblBat.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBat.setObjectName("lblBat")
        self.verticalLayout_2.addWidget(self.lblBat)
        self.lblAlt = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.lblAlt.setFont(font)
        self.lblAlt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlt.setObjectName("lblAlt")
        self.verticalLayout_2.addWidget(self.lblAlt)
        self.lblSpeed = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.lblSpeed.setFont(font)
        self.lblSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSpeed.setObjectName("lblSpeed")
        self.verticalLayout_2.addWidget(self.lblSpeed)
        self.lblAlt_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.lblAlt_4.setFont(font)
        self.lblAlt_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlt_4.setObjectName("lblAlt_4")
        self.verticalLayout_2.addWidget(self.lblAlt_4)
        self.btnTakeoff = QtWidgets.QPushButton(self.centralwidget)
        self.btnTakeoff.setGeometry(QtCore.QRect(670, 320, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.btnTakeoff.setFont(font)
        self.btnTakeoff.setObjectName("btnTakeoff")
        self.btnExt = QtWidgets.QPushButton(self.centralwidget)
        self.btnExt.setGeometry(QtCore.QRect(30, 450, 91, 41))
        self.btnExt.setObjectName("btnExt")
        self.btnMission = QtWidgets.QPushButton(self.centralwidget)
        self.btnMission.setGeometry(QtCore.QRect(850, 320, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.btnMission.setFont(font)
        self.btnMission.setObjectName("btnMission")
        self.DsgnInfo = QtWidgets.QLabel(self.centralwidget)
        self.DsgnInfo.setGeometry(QtCore.QRect(70, 70, 461, 211))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.DsgnInfo.setFont(font)
        self.DsgnInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DsgnInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.DsgnInfo.setObjectName("DsgnInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DRONE CONTROL CENTER"))
        self.DsgnBattery.setText(_translate("MainWindow", "0"))
        self.DsgnAltitude.setText(_translate("MainWindow", "0"))
        self.DsgnSpeed.setText(_translate("MainWindow", "0"))
        self.DsgnYaw.setText(_translate("MainWindow", "0"))
        self.lblBat.setText(_translate("MainWindow", "Batarya :"))
        self.lblAlt.setText(_translate("MainWindow", "Yükseklik:"))
        self.lblSpeed.setText(_translate("MainWindow", "Hız:"))
        self.lblAlt_4.setText(_translate("MainWindow", "Yaw:"))
        self.btnTakeoff.setText(_translate("MainWindow", "Kalkış"))
        self.btnExt.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.btnMission.setText(_translate("MainWindow", "Görev"))
        self.DsgnInfo.setText(_translate("MainWindow", "Bildirim Yok"))

